version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  reviewers:
    - "pi-hole/core-maintainers"
- package-ecosystem: pip
  directory: "/test"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  reviewers:
    - "pi-hole/core-maintainers"
# As above, but for development-v6
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development-v6
  reviewers:
    - "pi-hole/core-maintainers"
- package-ecosystem: pip
  directory: "/test"
  schedule:
    interval: weekly
    day: saturday
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development-v6
  reviewers:
    - "pi-hole/core-maintainers"
